# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b0f29a3893fda865ba89792fe85076de1124d239a81dc819520f7d31b4cef64102c4f0fd7b6341f71d5831de3283bcd4cd4eb7fca4e29d7fb2809480dc236d6

test:
  secret_key_base: 1d4bdc04887a245d5e990683861878cf8bce3f3b82beeeb56a24183a05da00d71e22048e268c952bbc96ecf2028b36bafd7aa783a72f636cfce595f7262ccfcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
